### ISSUE TITLE
Final navigation

### ISSUE THREAD

**Issue by justincaze** [alex96dev/MeetMate#104]
## Value proposition
As a user
I want to navigate to all pages using the navigation bar
in order to have a better overview
## Description

![Image](https://github.com/alex96dev/MeetMate/assets/155940239/5d3b9bcb-7b86-45b4-b8e9-15272256cec3)

## Acceptance criteria
- [ ] All the links should work
## Tasks
- [ ] Change the name frienbdlistPage to profilePage
- [ ] Change the joinPage button to go to the profilePage
- [ ] Delete the ProfileButton on the main page
- [ ] Change the friendlistPage to a component
