### ISSUE TITLE
Improvements CardForm

### ISSUE THREAD

**Issue by stellanw** [alex96dev/MeetMate#114]
## Value proposition
As a developer
I want to improve the CardForm component
In order to it works bug free and could be used dynamically without state problems

## Description
- The code should be simplified to run the CardForm bug free.
 
## Acceptance criteria
- [ ] the CardForm should work without error in create and edit mode

## Tasks
- [ ] Lift up all States by using "Zustand" in store.js
- [ ] Lift up functions in utils.js
- [ ] Reduce the two UseEffects in one
- [ ] Test functionality of create and edit feature
