### ISSUE TITLE
LoginPage small Styling Improvement

### ISSUE THREAD

**Issue by stellanw** [alex96dev/MeetMate#115]
## Value proposition
As a user
I want to see an visually appealing Login Page
In order to quickly understand which app I am going to use and where I can log in

## Description
- The LoginPage should be match with the overall app styling and spacing.

## Acceptance criteria
- [ ] The Login Page match the overall app styling and spacing 

## Tasks
- [ ] Add Spacing and placement
- [ ] Add Apps Name and Logo
